name: MERN APP CI

on:
  push:
    branches: [feature/yu-ci-cd-setup]
  pull_request:
    branches: [dev]

jobs:
  server-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build (Server)
        run: |
          cd server
          npm install
          npm run build

      # - name: Archive Server Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: server-artifact
      #     path: server/dist/

      - name: Push Build Files
        run: |
          cd server
          git push

  client-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build (Client)
        run: |
          cd client
          npm install
          npm run build

      # - name: Archive Client Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: client-artifact
      #     path: client/dist/

      - name: Push Build Files
        run: |
          cd client
          git push
